### ISSUE TITLE
Example workflow doesn't work

### ISSUE THREAD

**Issue by JPL4494** [Jonseed/Ollama-Node#1]
I installed the node on my dockerized invokeai container, and configured the python code to point to my ollama container. I can confirm the node works and is able to access the ollama container, but when I use the example workflow, there are errors on the flux denoise module and the workflow cannot run because there is no model set in the flux main model. I was able to get the metadata module working by deleting it and adding a new one, and recreating the connections.

I have no idea how to get the model issue working though, is there something I can do to get the workflow working? I can upload my JSON if you want, but I haven't done anything special besides recreating the denoise

### Model Error

![image](https://github.com/user-attachments/assets/474d6e00-3f82-4ac9-887f-732d820051f9)

#### Template

![image](https://github.com/user-attachments/assets/9abc0a6d-2cd7-46fc-aeda-d32819459208)

#### New

![image](https://github.com/user-attachments/assets/2da93570-e4d6-42b8-ba6c-f5af9d29c365)

**Comment by Jonseed** [comment]
Have you downloaded a working Flux model? All this node does it help generate a prompt with Ollama (using LLM models loaded in Ollama), nothing else. It doesn't download Flux models or anything like that. You have to do that in the model manager of Invoke.

**Comment by JPL4494** [comment]
Ah, I definitely missed that important step, haha. Sorry about that!
